"""ConvReadState added

Revision ID: 59ee740dfcd3
Revises: a551e8e507c6
Create Date: 2026-02-18 23:35:19.218894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59ee740dfcd3'
down_revision: Union[str, Sequence[str], None] = 'a551e8e507c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conv_read_state',
    sa.Column('conv_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('last_message_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['conv_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['last_message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('conv_id', 'user_id')
    )
    op.drop_index(op.f('idx_conv_unread_user'), table_name='conv_unread')
    op.drop_table('conv_unread')
    op.drop_table('conv_seen')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conv_seen',
    sa.Column('conv_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conv_id'], ['conversation.id'], name=op.f('conv_seen_conv_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('conv_seen_user_id_fkey')),
    sa.PrimaryKeyConstraint('conv_id', 'user_id', name=op.f('conv_seen_pkey'))
    )
    op.create_table('conv_unread',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conv_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('unread_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conv_id'], ['conversation.id'], name=op.f('conv_unread_conv_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('conv_unread_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'conv_id', name=op.f('conv_unread_pkey'))
    )
    op.create_index(op.f('idx_conv_unread_user'), 'conv_unread', ['user_id'], unique=False)
    op.drop_table('conv_read_state')
    # ### end Alembic commands ###
