"""updated fields in conversation table

Revision ID: ea9616401359
Revises: 3ef08145bcd6
Create Date: 2026-02-21 17:16:22.571127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea9616401359'
down_revision: Union[str, Sequence[str], None] = '3ef08145bcd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convreadstate',
    sa.Column('conv_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('last_message_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conv_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['last_message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('conv_id', 'user_id')
    )
    op.drop_table('conv_read_state')
    op.add_column('conversation', sa.Column('last_message_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('conversation_last_message_sender_id_fkey'), 'conversation', type_='foreignkey')
    op.create_foreign_key(None, 'conversation', 'message', ['last_message_id'], ['id'])
    op.drop_column('conversation', 'last_message_content')
    op.drop_column('conversation', 'last_message_sender_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('last_message_sender_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('conversation', sa.Column('last_message_content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conversation', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_last_message_sender_id_fkey'), 'conversation', 'user', ['last_message_sender_id'], ['id'])
    op.drop_column('conversation', 'last_message_id')
    op.create_table('conv_read_state',
    sa.Column('conv_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_message_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('last_read_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conv_id'], ['conversation.id'], name=op.f('conv_read_state_conv_id_fkey')),
    sa.ForeignKeyConstraint(['last_message_id'], ['message.id'], name=op.f('conv_read_state_last_message_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('conv_read_state_user_id_fkey')),
    sa.PrimaryKeyConstraint('conv_id', 'user_id', name=op.f('conv_read_state_pkey'))
    )
    op.drop_table('convreadstate')
    # ### end Alembic commands ###
